### PR TITLE
多段階に関連するモデルをexportする際に途中のオブジェクトが消える問題の修正

### PR DESCRIPTION
**Pull request by mizobuchi**
exportのincludeオプションにall_symbol以外のものが渡された時，オブジェクトの内容が出力されない問題の修正

### CODE REVIEW

**Comment by iruca3** [comment]
Thanks for your contribution. I want to merge this request, but I need test code.
Please provide the test.

**Comment by mizobuchi** [comment]
Thanks.
Please check it.

**Comment by iruca3** [comment]
It seems very nice bug fix. :+1:
Please squash your commits and I will merge.

**Comment by mizobuchi** [comment]
I squash my commits.
Would you merge this?

**Comment by iruca3** [comment]
Thanks, @mizobuchi !

**Pull request merged**
